# Generated by Django 4.1.2 on 2022-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_release',
            field=models.DateField(),
        ),
    ]
